'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Variable Name..")>  _
        Public Property VariableName() As String
            Get
                Return CType(Me("VariableName"),String)
            End Get
            Set
                Me("VariableName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Variable Type...")>  _
        Public Property VariableType() As String
            Get
                Return CType(Me("VariableType"),String)
            End Get
            Set
                Me("VariableType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Sub Arrival...")>  _
        Public Property SubArrival() As String
            Get
                Return CType(Me("SubArrival"),String)
            End Get
            Set
                Me("SubArrival") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Sub Type...")>  _
        Public Property SubType() As String
            Get
                Return CType(Me("SubType"),String)
            End Get
            Set
                Me("SubType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Function Type...")>  _
        Public Property FunctionType() As String
            Get
                Return CType(Me("FunctionType"),String)
            End Get
            Set
                Me("FunctionType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Inheritance...")>  _
        Public Property InheritanceName() As String
            Get
                Return CType(Me("InheritanceName"),String)
            End Get
            Set
                Me("InheritanceName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Import...")>  _
        Public Property ImportName() As String
            Get
                Return CType(Me("ImportName"),String)
            End Get
            Set
                Me("ImportName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Class Name...")>  _
        Public Property ClassName() As String
            Get
                Return CType(Me("ClassName"),String)
            End Get
            Set
                Me("ClassName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Variable Name")>  _
        Public Property clmVariableName() As String
            Get
                Return CType(Me("clmVariableName"),String)
            End Get
            Set
                Me("clmVariableName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property clmVariableNameWidth() As Integer
            Get
                Return CType(Me("clmVariableNameWidth"),Integer)
            End Get
            Set
                Me("clmVariableNameWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Variable Type")>  _
        Public Property clmVariableType() As String
            Get
                Return CType(Me("clmVariableType"),String)
            End Get
            Set
                Me("clmVariableType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property clmVariableTypeWidth() As Integer
            Get
                Return CType(Me("clmVariableTypeWidth"),Integer)
            End Get
            Set
                Me("clmVariableTypeWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Write Sub Name...")>  _
        Public Property SubName() As String
            Get
                Return CType(Me("SubName"),String)
            End Get
            Set
                Me("SubName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sub Arrival")>  _
        Public Property clmSubArrival() As String
            Get
                Return CType(Me("clmSubArrival"),String)
            End Get
            Set
                Me("clmSubArrival") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property clmSubArrivalWidth() As Integer
            Get
                Return CType(Me("clmSubArrivalWidth"),Integer)
            End Get
            Set
                Me("clmSubArrivalWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sub Type")>  _
        Public Property clmSubType() As String
            Get
                Return CType(Me("clmSubType"),String)
            End Get
            Set
                Me("clmSubType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property clmSubTypeWidth() As Integer
            Get
                Return CType(Me("clmSubTypeWidth"),Integer)
            End Get
            Set
                Me("clmSubTypeWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sub Name")>  _
        Public Property clmSubName() As String
            Get
                Return CType(Me("clmSubName"),String)
            End Get
            Set
                Me("clmSubName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property clmSubNameWidth() As Integer
            Get
                Return CType(Me("clmSubNameWidth"),Integer)
            End Get
            Set
                Me("clmSubNameWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Parameters Of Sub")>  _
        Public Property clmSubParameterList() As String
            Get
                Return CType(Me("clmSubParameterList"),String)
            End Get
            Set
                Me("clmSubParameterList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property clmSubParameterListWidth() As Integer
            Get
                Return CType(Me("clmSubParameterListWidth"),Integer)
            End Get
            Set
                Me("clmSubParameterListWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Inheritance")>  _
        Public Property clmInheritanceName() As String
            Get
                Return CType(Me("clmInheritanceName"),String)
            End Get
            Set
                Me("clmInheritanceName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property clmInheritanceNameWidth() As Integer
            Get
                Return CType(Me("clmInheritanceNameWidth"),Integer)
            End Get
            Set
                Me("clmInheritanceNameWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Importance")>  _
        Public Property clmImportanceName() As String
            Get
                Return CType(Me("clmImportanceName"),String)
            End Get
            Set
                Me("clmImportanceName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("150")>  _
        Public Property clmImportanceNameWidth() As Integer
            Get
                Return CType(Me("clmImportanceNameWidth"),Integer)
            End Get
            Set
                Me("clmImportanceNameWidth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Return Type")>  _
        Public Property clmReturnType() As String
            Get
                Return CType(Me("clmReturnType"),String)
            End Get
            Set
                Me("clmReturnType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property clmReturnTypeWidth() As Integer
            Get
                Return CType(Me("clmReturnTypeWidth"),Integer)
            End Get
            Set
                Me("clmReturnTypeWidth") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PropertyGenerator.My.MySettings
            Get
                Return Global.PropertyGenerator.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
